---
x-uffizzi:
  ingress:
    service: app
    port: 80
services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: always
    ports:
      - 80:80
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
    secrets: |-
      OPENAI_API_KEY
      OPENAI_ACCESS_TOKEN
      API_REVERSE_PROXY
      TIMEOUT_MS
