# fly.toml file generated for mooschatroom on 2023-02-22T23:58:42+08:00

app = "mooschatroom"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  API_REVERSE_PROXY = "https://chat.duti.tech/api/conversation"
  OPENAI_ACCESS_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJhbWJpdGVhbUB6b2hvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnZW9pcF9jb3VudHJ5IjoiSU4ifSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLTE4SkwxWldxR1RBSXVuY2cwRzF5T1NnaSJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjM5NWU4Yzg1YjhhYzc3YmYxNWYzMDJjIiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3NjM3NjIwMiwiZXhwIjoxNjc3NTg1ODAyLCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9mZmxpbmVfYWNjZXNzIn0.MWuAzjc2EvKokaT8Xm5E7SQsfEC5EH2yhAMTM2WAPXE4VVjqzIQta7qRuZO4mAGlo69X1BsrHghSNyWMV9-IqcutJCGYGGQtc-lswS0GrVChlAKO1H8s2H-J0ABD0qqYgndM_HwNbGMWp_pBTQ2c4fy8HBEZTrJmvW9XBDYom1wLKXL6CvLrtmv-jNulo3K6x4FTv2reLVVlZ4uw9doNDt1Nt9LEi2TYs-emxhkuFDw9lLuGncL5Bt9udL1XphxgrRr2fmxzcjkqiNJYlbfRhno0Db1uRFH4_4FMX4M8ucw4V1oAQRLtzc0d8N_Fw00mZ8RrAEDQlRQzYQHMHSu8SA"
  OPENAI_API_KEY = ""
  TIMEOUT_MS = 60000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3002
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
